# Model arguments
model_name_or_path: microsoft/Phi-3-mini-4k-instruct
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true
trust_remote_code: true

#LoRA arguments
#use_peft: true
#lora_r: 64
#lora_alpha: 32
#lora_dropout: 0.05
#lora_target_modules:
#- q_proj
#- k_proj
#- v_proj
#- o_proj
#- gate_proj
#- up_proj
#- down_proj

# Data training arguments
dataset_mixer:
  ikno/aoi_merge: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
do_train: true
evaluation_strategy: epoch # One of ["no", "steps", "epoch"]
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: phi
hub_strategy: every_save
learning_rate: 8.0e-06
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 5
output_dir: data/phi-sft
optim: adamw_torch
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
save_steps: 1
save_total_limit: 3
seed: 42
warmup_ratio: 0.1